### ISSUE TITLE
Color changes to SearchField

### ISSUE THREAD

**Issue by ponori** [pinterest/gestalt#1000]
<img width="916" alt="Screenshot 2020-07-08 11 35 12" src="https://user-images.githubusercontent.com/50343812/86957138-1ccba600-c10f-11ea-9843-5cd21ce63b64.png">

The border color should change to `colorGray100` (#494949)

**Comment by mziemer21** [comment]
This uses the same #ddd color variable as other borders so will check back on this after we have a solution for #978

**Comment by jennyscript** [comment]
Fixed by #1034
