### ISSUE TITLE
Divider color change

### ISSUE THREAD

**Issue by ponori** [pinterest/gestalt#1004]
<img width="645" alt="Screenshot 2020-07-08 11 41 52" src="https://user-images.githubusercontent.com/50343812/86957767-0c67fb00-c110-11ea-91b7-8525a4d58a3a.png">

The border color should change to `colorGray100` (#494949)

**Comment by jennyscript** [comment]
This uses the same `#ddd` color variable as other borders so will check back on this after we have a solution for #978

**Comment by jennyscript** [comment]
Fixed by #1021
