### ISSUE TITLE
Video controls should not invert in dark mode

### ISSUE THREAD

**Issue by ponori** [pinterest/gestalt#1006]
<img width="1105" alt="Screenshot 2020-07-08 11 45 16" src="https://user-images.githubusercontent.com/50343812/86958130-89937000-c110-11ea-9fb6-cbda797f439c.png">

All colors in the video controls should remain the same in light and dark modes.

**Comment by AlbertCarreras** [comment]
taking these one! Alberto Carreras

**Comment by AlbertCarreras** [comment]
Addressed on https://github.com/pinterest/gestalt/pull/1010
