### ISSUE TITLE
[Borders.css] Darkmode Translation to #ddd and addition to color schemes

### ISSUE THREAD

**Issue by AlbertCarreras** [pinterest/gestalt#1020]

**Comment by jennyscript** [comment]
We discussed a few things in slack. Please confirm @ponori but I think this is what we decided:

New color: `colorGray150 `
Light mode value: `#ddd`
Dark mode value: `#585858`

This should fix all issues like #1002 and related

**Comment by ponori** [comment]
@jennyscript Confirmed. Thanks!
