### ISSUE TITLE
Modal do not overlap Avatar Component

### ISSUE THREAD

**Issue by MateusGabi** [pinterest/gestalt#104]
## Code

```
// TodoCard Component
<Box
                alignItems="center"
                direction="row"
                display="flex"
                height={70}>
                <Box paddingX={1}>
                  <Avatar name={this.props.todo.titulo} size="md" />
                </Box>
                <Box paddingX={1}  flex="grow">
                  <Text bold>{this.props.todo.titulo}</Text>
                  <Text>{_timeToDone}</Text>
                </Box>
                <Box paddingX={1}>
                    <Button text="Feito" size="md" color="white" />
                </Box>
                </Box>
```

```
// UserProfileModal
<Modal
      accessibilityCloseLabel="close"
      accessibilityModalLabel="View random images"
      heading="Images"
      onDismiss={() => closeFunction()}
      size="lg"
    >
      <UserProfile />
    </Modal>
```

## Example:
![image](https://user-images.githubusercontent.com/14940643/38099770-7343abdc-3349-11e8-9294-c12fcad440bc.png)

**Comment by bradencanderson** [comment]
@notr0n can you provide a minimal example of the issue?

**Comment by MateusGabi** [comment]
@bradencanderson this issue was solved at `gestalt@0.79.1`. 
Example: https://github.com/MateusGabi/gestalt-issue-104

**Comment by MateusGabi** [comment]
@notr0n please, show me your `package.json`.

**Comment by notr0n** [comment]
@MateusGabi Thanks for your attention ,
![issue](https://user-images.githubusercontent.com/41227764/45215438-af505380-b2b2-11e8-98a2-3fe4c1b41489.png)

**Comment by notr0n** [comment]
@bradencanderson
That's what i talking about : 
![x11](https://user-images.githubusercontent.com/41227764/45219447-3657f880-b2c0-11e8-9f08-efd454dd208d.jpg)

and this is my App.js : 
![x22](https://user-images.githubusercontent.com/41227764/45219225-74a0e800-b2bf-11e8-8c1f-1fb1cd258a96.png)

The only thing thati want to do is when i click on the button to show MODAL it shows over Other Layers (sth like what z-index or zIndex do ! but they're not work here ! )

i also use `style={{overlay:{zIndex:1000}}}`  but i didn't work too !

**Comment by MateusGabi** [comment]
So weird! @notr0n, Your version of gestalt is outdated. Try update gestalt to 0.79.1, just run `npm install gestalt@latest`.

**Comment by notr0n** [comment]
@MateusGabi Now my gestalt releases 0.79.1 but i still have this problem : 
![x11](https://user-images.githubusercontent.com/41227764/45220342-12e27d00-b2c3-11e8-9fcc-f281f2265c8c.jpg)

**Comment by MateusGabi** [comment]
Wow, could you please fork this project (https://github.com/MateusGabi/gestalt-issue-104) and type a minimal code of `Book` and `Video` components? Let's solve this!

**Comment by notr0n** [comment]
@MateusGabi 
Done !
`https://github.com/notr0n/gestalt-issue-104/blob/master/modal.js`

**Comment by MateusGabi** [comment]
Is `<Video />` inside the modal?

**Comment by khapnm15dh110042** [comment]
Hello @notr0n, I guess you use Tabs in Gestalt, how do you load a new content when changing between those tabs. The documentation does not include the solution, I try to figure out but no hope, please give me any suggestion if you can. Thank you.

**Comment by christianvuerings** [comment]
Closing out. Feel free to re-open if still relevant.
