### ISSUE TITLE
Add these 4 icons to Gestalt Icon library

### ISSUE THREAD

**Issue by Warbring3r** [pinterest/gestalt#105]
https://www.dropbox.com/sh/5azccoy448fhmvp/AAC1BgLkrNTuOlNLi2wpJf1aa?dl=0

Their first use case will be on this on-pin-analytics page - https://app.zeplin.io/project/5a603a026e836180d2719bf0/screen/5abe760c63d2c61e5afd17cf

**Comment by MateusGabi** [comment]
Hi, I'm not Pinterester 😄 I guess you'd submit a PR.

**Comment by pfarejowicz** [comment]
Closed via #106
