### ISSUE TITLE
Checkbox / RadioButton ref: Flyout doesn't get correctly positioned when using Checkbox / RadioButton ref prop

### ISSUE THREAD

**Issue by AlbertCarreras** [pinterest/gestalt#1068]
![image](https://user-images.githubusercontent.com/10593890/88213173-37247a00-cc0d-11ea-8e04-675ab0195654.png)

position: `relative` cannot be removed.

**Comment by christianvuerings** [comment]
@AlbertCarreras could you investigate work-arounds?

**Comment by AlbertCarreras** [comment]
I think the solution is to set the positioning ref to an outer box.
