### ISSUE TITLE
Unnecessary network requests by Masonry when it is not rendered

### ISSUE THREAD

**Issue by Narutuffy** [pinterest/gestalt#1075]
I am conditionally rendering Masonry. Even though it is not rendered it is making unnecessary requests for the images. How do we prevent that?

**Comment by btraut** [comment]
Hi @Narutuffy! Can you share some code for how you're using Masonry? How are you conditionally it? If Masonry is not rendered (ie: not in the DOM), it can't possibly render items.

**Comment by dangerismycat** [comment]
Closing due to lack of action for over six months. If this is still an issue for you, please feel free to re-open.
