### ISSUE TITLE
Infinity` is an invalid value for the `height` css style property

### ISSUE THREAD

**Issue by bardiarastin** [pinterest/gestalt#109]
hello, i've used Masonry component and i face this warning
![image](https://user-images.githubusercontent.com/20615964/38363079-7c75b520-38e8-11e8-970f-78335739440a.png)

**Comment by bishwei** [comment]
Yup this is a bug - I think this happens in React 16.   Thanks for reporting!

**Comment by eshwarenm** [comment]
Sorry is this fixed, cause im still getting the same issue.

**Comment by bishwei** [comment]
@eshwarenm, yup you're right.  looks like i missed one more area.  
Fix here: https://github.com/pinterest/gestalt/pull/177

**Comment by InesArrom** [comment]
I just got the same bug which did not come out last week
