### ISSUE TITLE
Docs: can't open components in a new tab

### ISSUE THREAD

**Issue by christianvuerings** [pinterest/gestalt#113]
From one of our users:

> On https://pinterest.github.io/gestalt, I can't open pages from the menu on the left in a new tab.  Redirects to https://engineering.pinterest.com.  I am new to gestalt and having multiple tabs open is useful for figuring out how different components fit together.

**Comment by MateusGabi** [comment]
Yeah!!

## Use case:
> `Ctrl+click` or `right click -> open new table` in sidebar

**Comment by pfarejowicz** [comment]
Fixed this issue with #120 should go live to the site in the next release
