### ISSUE TITLE
https://gestalt.netlify.app/Installation doesn't render properly due to CORS issues

### ISSUE THREAD

**Issue by jmarthernandez** [pinterest/gestalt#1147]
#### Steps to reproduce 
1. Navigate to https://gestalt.netlify.app/Installation or click the link to Installation in the sidebar
2. /Installation renders and empty div and throws CORS errors in the console

#### Expected behavior
- Render this document https://github.com/pinterest/gestalt/blob/master/docs/src/Installation.md (I think)

#### Relevant logs and/or media (optional)
<img width="882" alt="Captura de pantalla 2020-08-14 a la(s) 9 33 54 p  m" src="https://user-images.githubusercontent.com/5953350/90303787-9b3a0700-de76-11ea-811f-32ba2928dcff.png">

**Comment by christianvuerings** [comment]
@jmarthernandez thanks for the report! We just made a PR with a potential fix: #1148
