### ISSUE TITLE
Adding error message handling to Typeahead

### ISSUE THREAD

**Issue by themindfuldev** [pinterest/gestalt#1156]
Similarly to https://github.com/pinterest/gestalt/issues/617, we would like to add error message handling to `<Typeahead>`.

This is what is needed:
- Adding 2 new optional props hasError and errorMessage.
- Consuming them to populate aria-invalid, aria-describedby and including <FormErrorMessage>.

By doing this, we will be able to start verifying error states using aria-invalid on unit tests using RTL.

Reference PR: https://github.com/pinterest/gestalt/pull/1155

**Comment by CalvinChhour** [comment]
I have some bandwidth so I will take this task, I'll have a PR up for this shortly :)

**Comment by dangerismycat** [comment]
I checked in with @CalvinChhour and @themindfuldev on Jan 14, and they're still planning on working on this at some point in the future. They're the ones who need the feature, so the development is on their schedule. 🙂

**Comment by dangerismycat** [comment]
@themindfuldev @CalvinChhour I'm going to close this issue for now, as it seems that the work is on hold and we're pausing active development on Typeahead until it goes through a more comprehensive design review. If you still need this feature, please feel free to re-open and contact us! 🙂
