### ISSUE TITLE
bug when rendering empty Box

### ISSUE THREAD

**Issue by hazem-a1** [pinterest/gestalt#1160]
first of all am a big fan 
great work i've been working with gestelt since  v 1.47.0

now im use  version 11.20.0 

when i render an box  hold a value  needs some check   or render based on prop  

like 

                    {process.process &&
                      process.process.score &&
                      process.process.score == 1 && <Text>33%</Text>}

it brings back a ZERO   0 

i dont have a time to track the bug  but its not from my code clearly

cause this pattern  happen every time  i try in an empty component 

thanks again for the great work <3

**Comment by christianvuerings** [comment]
@hazem-a1 could this be related to https://stackoverflow.com/questions/53048037/react-showing-0-instead-of-nothing-with-short-circuit-conditional-component ?

I would try `Boolean(process.score && process.process.score == 1) && <Text>33%</Text>` to confirm
