### ISSUE TITLE
Masonry performs differently between Safari iOS & Chrome

### ISSUE THREAD

**Issue by KotoriK** [pinterest/gestalt#1194]
As title. Detail will be described base on this [codesandbox example](https://tu5jl.csb.app/)
1. if remove minHeight from the root element in PageCard(I've commented it), on Safari all the cards will stacked together, on Chrome it will display correctly.
   but if "flexible" is set false on Masonry, Safari will render as Chrome does.
2.if add minHeight back, on Chrome it won't changed, on Safari it wont stack together, but gap won't be rendered on vertical.

This might be caused by different behaviour between Safari iOS and Chrome.

Environment:
Chrome 85 , Safari (iOS 13.4.1)

**Comment by dangerismycat** [comment]
I'm marking this as `wontfix`. I doubt this affects many of our users and we're not going to have the time to address this anytime soon.
