### ISSUE TITLE
Messed card grid with masonry

### ISSUE THREAD

**Issue by jonatassales** [pinterest/gestalt#1261]
I'm trying to create a grid like Pinterest with some cards, but somehow it's resulting in a weird grid

Codesandbox: https://codesandbox.io/s/quizzical-shockley-qp5op?file=/src/App.js

Am I missing something?

**Comment by willyau** [comment]
u may need to import the css as per https://gestalt.netlify.app/Installation#Dev

```
import 'gestalt/dist/gestalt.css';
```

**Comment by jonatassales** [comment]
Is there any way I can import only the css for masonry, for bundle size purposes. It worked BTW. Thanks
