### ISSUE TITLE
Can't access ModuleExpandableBase isCollapsed prop

### ISSUE THREAD

**Issue by lilcorey** [pinterest/gestalt#1307]
I'd like to access isCollapsed found in <ModuleExpandableBase/> so it can be passed to the child component of <Module.Expandable/> like so

```
  <Module.Expandable
    id="myModule"
    items={
      results.map(result => {
        return {
          title: result.name,
          summary: [result.info],
          children: <Component isCollapsed={!! PASS IsCollapsed HERE !!} place={result.data}/>
        }
      })
    }
    accessibilityExpandLabel="Expand the module"
    accessibilityCollapseLabel="Collapse the module"
    >
    </Module.Expandable>
```

The goal is to take action within the child when the Module item is expanded. If there is another method to do so without isCollapsed, any help would be appreciated! 
![image](https://user-images.githubusercontent.com/1939532/101583716-e2ea1e80-3990-11eb-9258-0a0fcd1b871f.png)

**Comment by dangerismycat** [comment]
Hey Corey! Check out this PR we just merged in: https://github.com/pinterest/gestalt/pull/1323

This adds a couple of new props to Module. I believe you should be able to use the `onExpandedChange` callback to accomplish what you're trying to do. If not, please re-open this issue and let us know where it's falling short. 🙂
