### ISSUE TITLE
Support flex-direction: row-reverse on Box

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#132]
We use this property in a chat view where the ordering and alignments of elements in a flexbox is reversed when it's from a user.

E.g., a message from another user (simplified):
![screen shot 2018-04-19 at 2 01 44 pm](https://user-images.githubusercontent.com/5060341/39018200-3969d5e8-43da-11e8-9e3f-0dce7a553d9f.png)

We'd then reverse that ordering for messages from the viewer and align the elements to the right-hand-side.

**Comment by christianvuerings** [comment]
@bradencanderson can we do this in JavaScript instead? Using `row-reverse` actually makes the keyboard navigation not flow correctly (so less accessible)

> “Authors must not use order or the -reverse values of flex-flow/flex-direction as a substitute for correct source ordering, as that can ruin the accessibility of the document.”
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items
Also https://www.w3.org/TR/css-flexbox-1/#order-accessibility

**Comment by bradencanderson** [comment]
Thanks @christianvuerings, I didn't know! We currently have a bunch of custom CSS that relies on `row-reverse`, so I'll update it to not use that in the future.
