### ISSUE TITLE
Image is really hard to use

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#137]
This is more of a general issue, but I thought I'd mention it here so the maintainers get the feedback: `Image` frequently collapses to zero height/width in dynamically sized containers and it's a pain in the butt to develop with. It would be great to have better defaults for `Image`, or maybe wrap it in a different component that is less clever about sizing.

**Comment by bradencanderson** [comment]
Here's a simple repro:

**Comment by chrislloyd** [comment]
Yes, I agree. I think having optional `width` and `height` property could solve a lot of the usability issues with Image. It's a pretty common pattern to wrap it with a Box that sets those constraints.
