### ISSUE TITLE
Massive performance issues with Masonry with scrollContainer set

### ISSUE THREAD

**Issue by JoaoCnh** [pinterest/gestalt#147]
I'm having a huge performance drop when using Masonry with scrollContainer set. When it is set, each component in the page re-renders. If I try to use PureComponent or shouldComponentUpdate each item of the Masonry doesn't measure correctly and doesn't set correctly.

If I just unset scrollContainer everything works fine and doesn't trigger a million re-renders. But then I can't use loadItems for infinite scrolling.

Am I doing something wrong? I'm using it just like the docs but with the scrollContainer set. loadItems doesn't work for me without scrollContainer

**Comment by btraut** [comment]
It's a limitation of Masonry currently that scrolls cause rerenders when `scrollContainer`, and you're right that `loadItems` doesn't work without it. I don't have anything to share just yet, but I'm working on a fix to this.

**Comment by JoaoCnh** [comment]
@btraut Ah ok. Nice to hear then. I'll keep watching this issue in case there are any updates. Thanks

**Comment by bishwei** [comment]
>  If I try to use PureComponent or shouldComponentUpdate each item of the Masonry doesn't measure correctly and doesn't set correctly.

@JoaoCnh would you be able to share some more details re: this (i.e. what props/state does the component depend on).  When measuring items, we try and reutilize existing nodes which means that subsequent items go through updates rather than mounts.  This is likely what's causing issues with your use of `PureComponent` so it would be great to get more details.

**Comment by JoaoCnh** [comment]
@bishwei I'm actually using Apollo's Query component. When I get results I render the Masonry and each card is just an image with a title and a subtitle basically. Like this:

```javascript
<Query query={QUERY}>
    {({ loading, error, data }) => {
      if (loading) {
        return <QueryLoading />;
      }

      if (error) {
        return <QueryError message={error.message} />;
      }

      return 
        <StyledContainer innerRef={this._setScroll} overflow="auto" fill="vertical">
            <Masonry
              minCols={1}
              flexible={true}
              columnWidth={400}
              virtualize={true}
              comp={MasonryTile}
              items={data.myStuff}
              scrollContainer={this._getScroll}
              loadItems={() => {
                 console.log("LOAD");
              }}
            />;
       </StyledContainer>
    }}
</Query>
```

**StyledContainer** is my styled-components div component that houses the scroll container.
**_setScroll** sets the ref and **_getScroll** returns the ref.

The MasonryTile components basically is just a div with an img an h1 and an h2. Nothing fancy

**Comment by JoaoCnh** [comment]
@bishwei @btraut Any updates on this? I've been working on other things but I was curious to know if there are any insights

**Comment by chrislloyd** [comment]
@JoaoCnh could you put together an example playground (or similar) for what you're seeing? You can fork https://codesandbox.io/s/k5plvp9v8v if that's easier. I'm really keen to look into this too but a seeing your exact setup will help debugging.

**Comment by JoaoCnh** [comment]
@chrislloyd I updated to the latest release and nothing renders in this [sandbox](https://codesandbox.io/s/23r7yrky3j).

I am still gonna try and replicate the slow scrolling. My example also involves images

**Comment by JoaoCnh** [comment]
@chrislloyd @bishwei @btraut Ok, I continued to work on this and I finally got good performance by using PureComponent on each Masonry Item. I was previously doing some stupid width and height assignment. Now they work great.

But there is still one lingering problem. It triggers renders on all the rest of my components.

My basic structure is:

```javascript
<Container>
  <Header />
  <Masonry />
  <Footer />
</Container>
```

I could set Header and Footer as PureComponents but I feel like maybe that is too much. I will do it for now but shouldn't Masonry just update itsetlf?

**Comment by chrislloyd** [comment]
Thanks for the example! It looks pretty good. Remember if you change either the reference to `comp` or the `items` Masonry needs to re-measure and re-layout all the items. PureComponent at least verifies that  `comp` won't change unnecessarily.

`Header` & `Footer` as PureComponent shouldn't really matter to Masonry's perf :)

Going to close this out but please let us know if you continue to have issues - always interested in improving Masonry's perf.

**Comment by JoaoCnh** [comment]
@chrislloyd Sorry for insisting but the problem I'm facing now is that every scroll on the Masonry container triggers a re-render of the full page. Is this intended?

If I remove the scrollContainer definition it doesn't trigger anything, thus the page runs smoothly

**Comment by chrislloyd** [comment]
Yeah, I think that's a legitimate problem with Masonry and scrolling ATM. You can verify the problem on pinterest.com currently now too. However, it might feel worse that it actually is because while it's still re-rendering it's not actually updating anything because the result hasn't changed.

I think @btraut was doing some work around this - do you have anything to share yet?

**Comment by btraut** [comment]
This week has been hell and I haven't been able to touch it, but yes, my prototype attempts to address this. I have it up and running where non-virtualized grids never re-render pins and virtualized grids only re-render after scrolling X pixels where X is based on the screen size.

**Comment by AkilLis** [comment]
Same issue on latest version.

**Comment by AkilLis** [comment]
@btraut any update?

**Comment by AmmarHalees** [comment]
Any update on this issue? 
@chrislloyd
