### ISSUE TITLE
How to use the image propertiy of RadioButton?

### ISSUE THREAD

**Issue by DongFang1314** [pinterest/gestalt#1497]
Steps to reproduce:
Code copied from https://gestalt.netlify.app/RadioButton#images does'n work.
1. code:
![image](https://user-images.githubusercontent.com/42634122/117536555-376ff380-b02e-11eb-8f70-d9f22f7f42a3.png)
2.page:
![image](https://user-images.githubusercontent.com/42634122/117536573-55d5ef00-b02e-11eb-9677-f11314fe4512.png)
3.source code
![image](https://user-images.githubusercontent.com/42634122/117536612-959cd680-b02e-11eb-85d9-22d25df05b66.png)
4.version
gestalt:latest 
![image](https://user-images.githubusercontent.com/42634122/117536633-b1a07800-b02e-11eb-9dd0-a83f9442bb4c.png)
react:16.8.6

**Comment by dangerismycat** [comment]
Hm…it's not clear from the screenshots you shared what's going on here. The code on the docs is live, in that it reflects what's currently exported from the library. Can you share a link to your actual code? Or can you repro the bug in a simplified form in a CodeSandbox (or similar)?

**Comment by DongFang1314** [comment]
Thanks for your reply.The reason for the proflem is the wrong import.
