### ISSUE TITLE
No way to pass input attributes to TextField

### ISSUE THREAD

**Issue by queeniema** [pinterest/gestalt#1532]
Example:

When I set `type="number"`, I want to be able to set `max`, `min`, and `step` (see [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#additional_attributes)).

Another example:

When I set `type="email"`, I want to be able to set `maxlength`, `minlength`, and `pattern` (see [attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email#additional_attributes)).

**Comment by dangerismycat** [comment]
Thanks for bringing this up, @queeniema! We discussed internally and we agree, this would be a good addition. We'll slot it into our priorities and let you know when we're able to address it. Thanks again! 🙂

**Comment by dangerismycat** [comment]
@queeniema Great news! We added a new NumberField component in #1760, which supports min/max/step. We don't currently have plans to add other attributes for `type="email"`, but we'll let you know if we do. Thanks for the suggestions!
