### ISSUE TITLE
Dropdown.Section fails with only one child

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#1533]
If only one child is present under Dropdown.Section then it fails.

Here is the codesandbox reproduction
https://codesandbox.io/s/awesome-proskuriakova-wnw5g

**Comment by ayeshakmaz** [comment]
Thanks for reporting this @zifahm! I've added a bug to our backlog, will let you know what it's fixed

**Comment by ayeshakmaz** [comment]
This should be fixed with version 25.0.0. Let us know if you still see an issue, and thanks again for reporting!
