### ISSUE TITLE
<Table> SortableTableHeader not compatible with sticky column

### ISSUE THREAD

**Issue by CalvinChhour** [pinterest/gestalt#1541]
Platform: (desktop web)

Steps to reproduce:

See [code sandbox](https://codesandbox.io/s/example-multiple-sticky-columns-forked-3i4th?file=/example.js) 
1. Setup table with sticky columns
2. Use SortableTableHeader 

Expected Result: Should be sticky without issues
![intended](https://user-images.githubusercontent.com/6954364/121236099-d3219900-c852-11eb-92e5-1d097157c4fd.gif)

Actual Result: The header doesn't follow the sticky behavior
![unintended](https://user-images.githubusercontent.com/6954364/121236102-d452c600-c852-11eb-929c-7d4fe65b023f.gif)

Please add either a screenshot or a video to help us quickly identify the issue.

**Comment by ayeshakmaz** [comment]
Thanks for reporting this @CalvinChhour. We have a ticket for this functionality in our backlog, I'll keep you posted here when it's been added :)

**Comment by ayeshakmaz** [comment]
Hi @CalvinChhour, this should be working now with v27.3.0. Let us know if you have any issues, and thanks again for reporting!

**Comment by CalvinChhour** [comment]
Looks like things are working on our end, thanks for the update and quick turnaround!
