### ISSUE TITLE
Button: Disabled buttons aren't styled as disabled on Safari / iOS

### ISSUE THREAD

**Issue by jackhsu978** [pinterest/gestalt#1556]
Platform: (desktop web | mobile web)

Steps to reproduce:

1. Open https://gestalt.netlify.app/Button#type-roles in Safari
2. Click on "Disable buttons"

Expected Result: Text colors of all buttons change.
![Screen Shot 2021-06-15 at 11 13 09 AM](https://user-images.githubusercontent.com/5341184/122102900-cb21a600-cdca-11eb-87b7-6fa352d2c6c3.png)

Actual Result: Only the last one (the link) has text color changed. Text colors for the buttons don't change.
![Screen Shot 2021-06-15 at 10 57 27 AM](https://user-images.githubusercontent.com/5341184/122102911-d07ef080-cdca-11eb-87ab-634c17ce5f30.png)

I found that versions prior to v5.10.0 work. The PR in v5.10.0 https://github.com/pinterest/gestalt/pull/951 introduced this bug. It looks like iOS/Safari has a UI bug where a button with `pointer-events: none` doesn't get repainted after its color CSS attribute has been updated.

NOTE: this is also [logged in JIRA](https://jira.pinadmin.com/browse/BUG-127975).

**Comment by dangerismycat** [comment]
This was fixed by #1584.
