### ISSUE TITLE
Avatar should fallback to default letter if image fails to load

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/gestalt#156]
If the image fails to load, it should just switch to using the default letter version. We had this issue recently on the docs where Avatars were showing broken images, when we could fall back to something better in that case.

**Comment by danedavid** [comment]
Can I work on this ?

**Comment by danedavid** [comment]
@chrislloyd  I've raised PR by converting Avatar to stateful component. If there is any other way, please comment and I shall make necessary changes

**Comment by danedavid** [comment]
shouldn't we close this by #167
