### ISSUE TITLE
Flex gap breaks flex-grow and flex-shrink behaviour of children

### ISSUE THREAD

**Issue by keyworks** [pinterest/gestalt#1630]
Platform: desktop web
Gestalt version: 21.17.13.

## Steps to reproduce:

Use the following code 
```
<Flex width={400} alignItems="end" gap={2}>
  <Box flex="grow">
    <TextField id="pinId" label="Pin ID" onChange={() => {}} />
  </Box>
  <Box flex="shrink">
    <Button text="Add Pin ID" />
  </Box>
</Flex>
```

**Expected:**
![Screen Shot 2021-08-16 at 6 07 48 PM](https://user-images.githubusercontent.com/590451/129647934-c5cb09d7-bd3b-4956-b4ce-9d167b6c77f5.png)

**Actual:**
![Screen Shot 2021-08-16 at 6 01 37 PM](https://user-images.githubusercontent.com/590451/129647754-82b2bc7d-1b12-4b0c-87b1-96f4be2e6705.png)

Root issue seems to be that using `gap` will add wrapper divs around `<Box flex="grow">` and `<Box flex="shrink">` which disables flex-grow and flex-shrink behaviour. Instead of using wrapper divs to implement `gap` I think there could be a css approach to this like using the `gap` css property. Alternatively, we could intersperse whitespace divs instead of wrapping the divs.

This is a pretty unfortunate gotcha which makes it hard for me to recommend `Flex.gap` to developers not willing to put in the time to understand and debug HTML/CSS. 

## Workaround

The workaround is to avoid using `Flex` and `gap` but instead use `Box` and margins.
```
<Box width={400} display="flex" alignItems="end">
  <Box flex="grow" marginEnd={2}>
    <TextField id="pinId" label="Pin ID" onChange={() => {}} />
  </Box>
  <Box flex="shrink">
    <Button text="Add Pin ID" />
  </Box>
</Box>
```

**Comment by christianvuerings** [comment]
@keyworks is another solution to use `Flex.Item`?

```jsx
<Flex width={400} alignItems="end" gap={2}>
  <Flex.Item flex="grow">
    <TextField id="pinId" label="Pin ID" onChange={() => {}} />
  </Flex.Item>
  <Flex.Item flex="shrink">
    <Button text="Add Pin ID" />
  </Flex.Item>
</Flex>
```

https://codesandbox.io/s/example-flex-item-qwtwh?file=/example.js

/cc @dangerismycat

**Comment by dangerismycat** [comment]
Agreed, this is why we added Flex.Item. We do plan to add additional props to that child component eventually, but I believe the `flex` prop should accomplish what you're looking for here.

**Comment by keyworks** [comment]
Thanks, that works for me. I missed `Flex.Item` in the documentation. 

Suggestion: It could be helpful if these components appeared in the navigation so that they are easier to discover. Something like this: 
![Screen Shot 2021-08-23 at 2 33 10 PM](https://user-images.githubusercontent.com/590451/130522394-2bd0fabf-afc2-481e-bbfc-0ec30721a7e6.png)
