### ISSUE TITLE
Module iconButton firing extra events when receiving keypress

### ISSUE THREAD

**Issue by themindfuldev** [pinterest/gestalt#1721]
Platform: desktop web

Steps to reproduce:

1. On a `Module.Expandable`,  performa a tab focus over an `iconButton` from a `Module` and hit space
2. Additionally to the button's action, the module will also collapse/expand.

Expected Result:
Actual Result: No module collapsing/expanding should happen, only the button's action.

Please add either a screenshot or a video to help us quickly identify the issue.

https://user-images.githubusercontent.com/764487/135550437-d494cd88-7b7e-46de-a784-cfb90cd6c862.mov

**Comment by dangerismycat** [comment]
@themindfuldev #1722 fixed this issue, correct? If not, feel free to re-open 🙂
