### ISSUE TITLE
Flyout not compatible with RTL

### ISSUE THREAD

**Issue by papigers** [pinterest/gestalt#175]
code sandbox here:
https://codesandbox.io/s/ojrwr8r02z

The bottom section contains the flyout demo straight from gestalt's website, only the direction has changed to rtl via html dir property.

**Comment by chrislloyd** [comment]
Thanks for the issue! Yes, we’ve only _just_ started to support RTL(see #122 as the start). There are also various other components that don’t support it yet (Maso Roy being the main one).

It think this is a good issue to track. I know Flyout is a little difficult to work with and my intention was to revamp a lot of this (and also address RTL) when #168 lands so we can use portals and new context.

However happy to accept PRs in the meantime to add this. Let me know if you need any help getting started.

**Comment by papigers** [comment]
Will do my best to help whenever I'd find the time :)

**Comment by papigers** [comment]
I found it difficult to find out where it all goes wrong in the Flyout code when the HTML direction is RTL. I eventually made my own Flyout using react portals, that creates the flyout modal with absolute positions under the body tag. I used much of the current flyout code for deciding flyout directions etc...

@chrislloyd Would you like me to fork your react 16 + PR, and apply those changes there?

On an entirely different subject, Masonry - would it be ok to replace `left` and `margin-left` styles with `right` and `margin-right` when RTL is required? I'm asking because I know that `top` and `left` are usually preferable to use.

**Comment by christianvuerings** [comment]
https://codesandbox.io/s/gestalt-flyout-rtl-y47op This issue has since been fixed. Thank you @papigers for raising it.

![image](https://user-images.githubusercontent.com/127199/74950582-2c429080-53b4-11ea-90ef-3e45b87f6232.png)
