### ISSUE TITLE
Dropdown: When changinn hover focus event is bubbling up to outside component

### ISSUE THREAD

**Issue by manvoid** [pinterest/gestalt#1793]
Platform: desktop web and mobile web

Steps to reproduce:

1. Use the dropdown with al least two items
2. Have a onFocus handler outside the Dropdown
3. When changing hove over the items the onFocus event is going to be triggered

Expected Result: Focus event not triggered
Actual Result: Focus event is triggered

This is causing issues when a page has a custom onFocus event handler. Ex: Closeup.js

**Comment by dangerismycat** [comment]
@manvoid Has this issue been fixed? If so, please feel free to close 🙂

**Comment by AlbertCarreras** [comment]
moved internally
