### ISSUE TITLE
Dropdown: Positioning when scrolling not working when inside a fixed component

### ISSUE THREAD

**Issue by manvoid** [pinterest/gestalt#1794]
Platform: desktop web and mobile web

Steps to reproduce:

1. Use a Dropdown inside a fixed positioned component (ex: searchbar)
2. Open the Dropdown and scroll the page

Expected Result: The Dropdown should follow the anchor element correctly
Actual Result: The Dropdown lags and the position is incorrect respect of the anchor element

https://user-images.githubusercontent.com/700818/144287102-ff978b53-4c0c-4f89-ad2e-543dde14b4a0.mp4

**Comment by dangerismycat** [comment]
@manvoid Has this issue been fixed? If so, please feel free to close 🙂

**Comment by manvoid** [comment]
Fixed in https://github.com/pinterest/gestalt/pull/1819
