### ISSUE TITLE
NumberField able to enter the letter "e" also the charachter " . " (period)

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#1830]
Steps to reproduce:

1. Go to docs under NumberField
2. Enter characters like ".e" or "e" or "."

Expected Result: Should not be able to enter these characters
Actual Result: character like "." and "e" is being able to enter

Please add either a screenshot or a video to help us quickly identify the issue.

![Screenshot from 2021-12-29 22-10-40](https://user-images.githubusercontent.com/3761062/147684569-be624c66-0c19-4a5c-a888-c2c5923796ba.png)

**Comment by dangerismycat** [comment]
This is expected behavior. You can confirm [on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). The reason why is covered [on StackOverflow](https://stackoverflow.com/questions/31706611/why-does-the-html-input-with-type-number-allow-the-letter-e-to-be-entered-in).

**Comment by zifahm** [comment]
ohh floating-point numbers and the exponent!!

**Comment by zifahm** [comment]
btw @dangerismycat  when I input the number 0 as the first input, it skips the number. Is there a workaround?

**Comment by dangerismycat** [comment]
Hey @zifahm-

Good catch! You're right, that is different behavior from the native `<input type="number">`. However, this is expected, given the parsing that component does internally to make working with counts easier. For numerical data that should allow leading 0's, TextField would be a better choice. And yes, ZIP codes are a perfect example of that type of data. 🤦 I'll update our docs to use a different example on NumberField, and add more nuance to the difference between NumberField and TextField on both pages.

Thanks for the heads-up!

**Comment by zifahm** [comment]
Sure, no problem. But the good thing about numberfield was on mobile it would inovke the numpad rather than the full keyboard. I think just setting the pattern on <input/> would also invoke it for text field i suppose.
```<input pattern="[0-9]*" />```

**Comment by dangerismycat** [comment]
Ah — check out the [Related section on NumberField](https://gestalt.pinterest.systems/numberfield#Related), or the [Props section on TextField](https://gestalt.pinterest.systems/textfield#Props). You'll want to use `<TextField type="tel">` for telephone numbers.

**Comment by zifahm** [comment]
OMG!!!
