### ISSUE TITLE
Gestalt Docs Broken for IE11 (Windows 8.1)

### ISSUE THREAD

**Issue by pfarejowicz** [pinterest/gestalt#197]
Currently, Gestalt Docs are not supported on IE11 browsers, a blank screen appears
![image](https://user-images.githubusercontent.com/7877010/40248007-5319dc62-5a83-11e8-8551-76b50e6f5bad.png)
Seeing this error in the console
```
var DefaultLayoutSymbol = Symbol('default');
'Symbol' is undefined
var UniformRowLayoutSymbol = Symbol('uniformRow');
```
Feel free to close if we are not concerned with support for IE

**Comment by christianvuerings** [comment]
Closing out. Feel free to re-open if still relevant.
