### ISSUE TITLE
Async compatibility

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/gestalt#216]
Turning on the `StrictMode` component it looks like the following components aren't React Async compatible. This is a meta issue to track progress towards updating these components.

- [x] SelectList
- [x] TextArea
- [x] TextField
- [x] Masonry
- [x] ScrollContainer

**Comment by pfarejowicz** [comment]
All changes except `Masonry` went out in `v0.72.0`, the last change will go out in `v0.73.0`
