### ISSUE TITLE
Broken search on https://gestalt.pinterest.systems/ 

### ISSUE THREAD

**Issue by christianvuerings** [pinterest/gestalt#2244]
**Steps to reproduce**:
1. https://gestalt.pinterest.systems/ 
2. Search for modal

**Expected Result**:
Modal page shows when you click the first link

**Actual Result**:
All of the links are broken:

- https://gestalt.pinterest.systems/component_overview#card-0
- https://gestalt.pinterest.systems/component_status
- https://gestalt.pinterest.systems/roadmap#ModalSheet-component-(Mobile-web)
- https://gestalt.pinterest.systems/roadmap#ModalSheet-component-design-guidelines-(AndroidiOS)
- https://gestalt.pinterest.systems/design_tokens#Background-color

![image](https://user-images.githubusercontent.com/127199/182307800-a2cf84c6-14e7-406d-bb06-f5a07ef7e5fd.png)

**Comment by christianvuerings** [comment]
@dangerismycat did we ever implement re-indexing Algolia whenever we push to master? Example of how we can set this up: https://pipedream.com/blog/reindex-algolia-on-github-releases/. That should have avoided this bug
@ayeshakmaz the bug is most likely caused by #2214

**Comment by dangerismycat** [comment]
I added redirects for all old paths this afternoon, and kicked off another recrawl. As far as I can tell, search is working again and the redirects are working as well. Feel free to reopen if you still see this issue.

And I haven't had a chance to finish implementing per-merge recrawls (Algolia customer service on free plans is slooooowwww), but it's on my list for this sprint or next.

**Comment by christianvuerings** [comment]
@dangerismycat awesome, thank you Ryan!
