### ISSUE TITLE
Markdown pages: Auto-reload doesn't work

### ISSUE THREAD

**Issue by christianvuerings** [pinterest/gestalt#2313]
Platform: web

Steps to reproduce:

1. Pull the latest Gestalt code
2. Run `yarn start`
3. Go to http://localhost:8888/get_started/developers/development_process
4. Make a change to `docs/markdown/get_started/developers/development_process.md`

Expected Result: The page updates with the new text
Actual Result: The page doesn't update - we need to do a manual reload

Caused by #2227

**Comment by christianvuerings** [comment]
Most likely root cause is that we're using a dynamic page route: `docs/pages/[...id].js` for the markdown pages

**Comment by dangerismycat** [comment]
Closing as `wontfix` — it'd be great to address this someday but we simply don't have the resources right now for a nice-to-have
