### ISSUE TITLE
HMR not working sometimes.

### ISSUE THREAD

**Issue by debanjanbasu** [pinterest/gestalt#256]
HMR was working perfectly fine with gestalt 0.73.0. This is no longer happening with version 0.74.0. May I know what were the changes really made under the hood, which might cause this?

**Comment by chrislloyd** [comment]
Hi @debanjanbasu you can see the difference using [Github's compare feature](https://github.com/pinterest/gestalt/compare/v0.73.0...v0.74.0). Nothing jumps out at me that looks like it would affect HMR - how did you narrow down the problem to Gestalt specifically?

**Comment by christianvuerings** [comment]
@debanjanbasu since then we've made a lot of changes (E.g. moving away from `concurrently`). Could you check if this is still an issue for you? If so, feel free to re-open & attach a reproducible test case
