### ISSUE TITLE
[request] Noninteractive state on IconButton

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#257]
I'd like to disable the hover state on an IconButton while i'm waiting for code split chunks.

A motivating example:

```js
let FlyoutComponent = null;

class App extends Component {
  state = { loaded: false, open: false };
  componentDidMount() {
    import('./FlyoutComponent').then(fc => { FlyoutComponent = fc; this.setState({ loaded: true }); });
  }

  render() {
    return (
      <>
        <IconButton disabled={!this.state.loaded} onClick={() => this.setState({ open: true })} />
       <Flyout open={this.state.open} />
         {FlyoutComponent ? <FlyoutComponent /> : null}
       </Flyout>
      </>
    )
  }
}

**Comment by bradencanderson** [comment]
More generally, this would be really helpful during the time between when the browser renders the SSR'd markup and when the button interactive (for some case-specific definition of interactivity).

**Comment by bradencanderson** [comment]
Yes, please! I haven't gotten a chance but it's definitely useful. I have
buy-in from the maintainers so merging shouldn't be an issue if the
implementation is good.

**Comment by rahilvora** [comment]
@bradencanderson Thank you for your response. I understand what you are want to achieve here with the example given above. Can you please direct me right direction of where I need to make changes to achieve the requested goal.
