### ISSUE TITLE
[Request] <Box/> flex prop sets box to display="flex" automatically 

### ISSUE THREAD

**Issue by mminute** [pinterest/gestalt#267]
atm one must specify `<Box display="flex" flex="grow"/>`
It would be preferable to simplify specify `<Box flex="grow" />`

**Comment by jackhsu978** [comment]
IIUC, `display="flex"` declares that this element is a flex container, and `flex="grow"` declares that this is a flex item and would grow based on available space. These props are independent.

**Comment by chrislloyd** [comment]
Yes, @jackhsu978 totally correct. I think the best change to fix this would be to update Box to be Flex by default.

```jsx
<Box />
<Box display="flex" />
<Box display="inlineBlock" />
// would become
<Box display="block" />
<Box />
<Box display="inlineBlock" />
```

It would avoid the confusing case of all the Flex properties only applying in certain situations and also _most_ usages of Box are flex or should be flex.

**Comment by christianvuerings** [comment]
Closing out since this issue hasn't been touched in the last few months
