### ISSUE TITLE
Issues navigating dropdown menu when NVDA is on

### ISSUE THREAD

**Issue by mellis481** [pinterest/gestalt#2735]
Platform: desktop web

Steps to reproduce:

1. Open NVDA.
2. Visit [Codesandbox](https://codesandbox.io/s/04bwrr?module=/example.js) example (which comes directly from the Gestalt documentation [here](https://gestalt.pinterest.systems/web/dropdown#Truncation))
3. Focus "Menu" button and click enter to open the menu.
4. Press down arrow repeatedly to cycle through the menu items.

Expected Result:  A user should be able to cycle through the menu options without issue.

Actual Result: When NVDA is on, visual focus gets stuck on menu item 2, but the virtual cursor appears to continue to other DOM elements, even ones outside of the menu.

[Here](https://mellis481.tinytake.com/msc/ODAxMzA2M18yMTE1MDEwMg) is a video demonstrating issue

I'm wondering if this is an issue with your Dropdown component or an issue with NVDA. I do not see this behavior with VoiceOver.

**Comment by AlbertCarreras** [comment]
@mellis481 Thanks for reporting this issue. Gestalt is an open-sourced project; however our only official customer is Pinterest web. Due to limited resources available to attend external requests, we are going to close this issue. Thanks for your understanding.
