### ISSUE TITLE
Rename the prop "shape" to "corners"

### ISSUE THREAD

**Issue by jackhsu978** [pinterest/gestalt#288]
Technically the shape should be called rectangle because width and height do not have to be the same. I think "square" is a bit misleading.

**Comment by rahilvora** [comment]
Hey Jack, 
I am new to open source contribution and I would like to contribute to this issue. Can you please explain what exactly is required here so that I can understand it more clearly and start working on it.

Thanks,
Rahil Vora

**Comment by jackhsu978** [comment]
@rahilvora thank you for volunteering! Some gestalt components have a prop named shape, which basically described the border radius of the component. Possible values are circle, rounded, and square. I find square to be a little misleading to represent the 0 border radius case because square is a special kind of rectangle where width = height. I think it’s more clear if we rename square to rectangle.

**Comment by bradencanderson** [comment]
@jackhsu978 I believe "square" here means "square corners", not "square the shape". One of the definitions of "square" is "having right angles".

**Comment by bradencanderson** [comment]
Maybe it would be better to rename to prop. `corners="square", corners="rounded", corners="circle"`.

**Comment by rahilvora** [comment]
if shape means the shape of the corners then I agree with the @bradencanderson suggestion.

**Comment by jackhsu978** [comment]
Yes, I agree. Renaming `shape` to `corners` is a better idea.

**Comment by rahilvora** [comment]
WIll work on this issue.

**Comment by rahilvora** [comment]
I have fixed this issue. Can someone authorize me to push my branch and create a pull request.

**Comment by pfarejowicz** [comment]
@rahilvora anyone should be able to fork the repo and create a pull request to master from their fork. Are you trying to directly create a branch in this repo and not a fork?

**Comment by rahilvora** [comment]
Yes, I am trying to do it directly.

**Comment by pfarejowicz** [comment]
@rahilvora we prefer to use the fork and create a pull request off of the branch in the forked repo. You can make a fork of `pinterest/gestalt` and set your local origin to point to that and your local upstream to here. That should allow you to push and then create a pull request without any new permissions needed

**Comment by rahilvora** [comment]
Sure Peter, Thanks.

**Comment by rahilvora** [comment]
PR for this issues https://github.com/pinterest/gestalt/pull/301

**Comment by christianvuerings** [comment]
Closing out. Feel free to re-open if still relevant.
