### ISSUE TITLE
Next.js 13 support

### ISSUE THREAD

**Issue by mohammad-saadati** [pinterest/gestalt#2926]
do you have any plan to add support for nextjs 13 in the future?

**Comment by dangerismycat** [comment]
No specific plans. What specific support/features are you interested in?

**Comment by mohammad-saadati** [comment]
i mean ssr support, right now it gives useContext usage error on server side.

**Comment by dangerismycat** [comment]
What specific error are you seeing, and in what specific situation(s)?

**Comment by mohammad-saadati** [comment]
when i want to use gestalt components on server side it gives show error because useContext hook is used in  gestalt components and it is not allowed in server side components.

sth like this issue :
https://stackoverflow.com/questions/74311376/using-react-context-with-nextjs13-server-side-components

**Comment by dangerismycat** [comment]
Ah ok, I see. It's not anything we're prioritizing now, but we'll probably address it when we start playing around with RSC in the main Pinterest repo in the future.

I'm closing this issue but thanks for surfacing it! Definitely something we'll keep in mind.
