### ISSUE TITLE
Important - Masonry not working! Neither in the docs, nor in codesandbox!

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#3037]
Masonry is not working. Neither in the docs nor in codesandbox.

https://codesandbox.io/s/xdspq3

https://gestalt.pinterest.systems/web/masonry

Have not  checked what's causing this problem. Will update after review!

**Comment by zifahm** [comment]
Looks like this PR is the issue
https://github.com/pinterest/gestalt/pull/2955

**Comment by dangerismycat** [comment]
Thanks for the quick bug catch! Just fixed, will merge when CI is 🟢

**Comment by zifahm** [comment]
When does gestalt merge with Pinterest? I thought it did during every new gestalt release. @dangerismycat

**Comment by dangerismycat** [comment]
Gestalt is just another dependency, so as with any dependency change, it has to be upgraded within the main Pinterest web repo.

**Comment by zifahm** [comment]
What version are you guys on right now? @dangerismycat
