### ISSUE TITLE
Bundling gestalt with js includes all the components

### ISSUE THREAD

**Issue by 92anurag** [pinterest/gestalt#306]
Is there a way to use specific component without including rest of the components so as to keep my minified js file small.

Currently its bundling all the components. Please let me know how to do that.

**Comment by chrislloyd** [comment]
Hi @92anurag, we export an ES6 version of the library so compatible bundlers (like Rollup) are able to tree-shake away any unused components. We currently bundle the required CSS for all components but that’s much harder to selectively import.
