### ISSUE TITLE
How to set custom color for <Text> and <Heading>

### ISSUE THREAD

**Issue by lilcorey** [pinterest/gestalt#3075]
**Component: Gestalt**

Platform: (desktop web)

Steps to reproduce:

1. https://gestalt.pinterest.systems/web/text#Colors or https://gestalt.pinterest.systems/web/heading
2. Both components have a `color` attribute. I need to use custom colors in these components. Using `style={{color: 'blue'}}` doesn't work, nor does setting hex value directly `color='#010101`. 

Expected Result: Some mechanism to set text color (like hex values) outside the supported Gestalt color scheme.
Actual Result: From testing myself + Gestalt docs I can't find a way to use custom color. If this is supported could documentation be added? If not, can custom color be added?

Add Pin, board or profile URLs that were used (if applicable):

Please add either a screenshot or a video to help us quickly identify the issue.

**Comment by rlingineni** [comment]
Hey Cory, sent you a message via our internal slack
