### ISSUE TITLE
Not a bug but a doubt. Not sure where else to post.

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#3082]
If you go [here](https://www.pinterest.com/business/business-access) in pintrest and look at the side nav. 
All Groups are expanded by default. How do you make this exapded by default?

I actually patch packaged it made this state to true [here](https://github.com/pinterest/gestalt/blob/c587d60db232bd7c62492bd903b4e6ff9b59356e/packages/gestalt/src/SideNavigationGroup.js#L133).
Is there a way how you guys make this happen in Pinterest?

**Comment by zifahm** [comment]
@dangerismycat quick help?

**Comment by AlbertCarreras** [comment]
@zifahm  Thanks for reporting this issue. Gestalt is an open-sourced project; however our only official customer is Pinterest web. Due to limited resources available to attend external requests, we are going to close this issue.  Thanks for your understanding.
