### ISSUE TITLE
Masonry unmounts grid items on window resize causing Video component to restart playback

### ISSUE THREAD

**Issue by keyworks** [pinterest/gestalt#311]
On window resize masonry will unmount and mount grid items. This is fine for images, but for videos, it will restart its position to 0. 

For example see this video (you will have to full screen): https://www.pinterest.com/pin/803962970955784053/

Repro steps:
- Load Video component as Masonry grid item
- Play video
- Resize window
- Observe video restarts playback to 0.

**Comment by chrislloyd** [comment]
This is an unavoidable consequence of virtualization. I recommend externalizing the play state of the video if you want it be preserved across re-layouts.
