### ISSUE TITLE
Collage component not working with Nextjs

### ISSUE THREAD

**Issue by Gurnoorkalsi** [pinterest/gestalt#3157]
**Project: BUG**
**Type: Bug**
**Component: Gestalt**

Platform: desktop web 

Steps to reproduce:

1. Tried using the Collage Component in a project with create-next-app
2. Collage appears as a horizontal grid with space
3. I also had tailwind installed

Expected Result: Collage should work as prescribed
Actual Result: I doesn't work 

Add Pin, board or profile URLs that were used (if applicable):
![Screenshot from 2023-08-24 12-39-46](https://github.com/pinterest/gestalt/assets/29943185/38845dc6-1360-4ef1-84bf-70844202935d)
![Screenshot from 2023-08-24 12-41-16](https://github.com/pinterest/gestalt/assets/29943185/5df4dc41-c203-41de-a913-14ef9b139d69)

Please add either a screenshot or a video to help us quickly identify the issue.

**Comment by AlbertCarreras** [comment]
@Gurnoorkalsi Thanks for reporting this issue. Gestalt is an open-sourced project; however our only official customer is Pinterest web. Due to limited resources available to attend external requests, we are going to close this issue.  Thanks for your understanding.
