### ISSUE TITLE
Masonry comp function receives items that are not in the items prop for Masonry

### ISSUE THREAD

**Issue by Jimmy-C** [pinterest/gestalt#318]
Synced up with Will Yau on the bug.
Looks like it's related to this change:https://github.com/pinterest/gestalt/commit/f6c683b66b2d8b0ec87db283418459e87160a21f
where items and itemsToRender are out of sync during the lifecycle.

**Comment by willyau** [comment]
Fixing here: https://github.com/pinterest/gestalt/pull/319
