### ISSUE TITLE
Support autocomplete=off in text inputs

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#328]
Not sure when this regression happened, but Gestalt TextFields just started showing the browser autocomplete dropdown. This is a problem everywhere we implement custom autocomplete functionality.

**Comment by bradencanderson** [comment]
Example: 
![screen shot 2018-08-31 at 4 00 59 pm](https://user-images.githubusercontent.com/5060341/44939019-14e29400-ad37-11e8-9b76-8b80d54e4924.png)

**Comment by bradencanderson** [comment]
@jennyscript could it be related to https://github.com/pinterest/gestalt/commit/66ddb17102c3a790a2c1c1e9dd761bf5fbfc8bd2?

**Comment by christianvuerings** [comment]
@bradencanderson Not sure what caused it but you should be able to set `autoComplete="off"` to disable this behavior

**Comment by bradencanderson** [comment]
Thanks @christianvuerings, I missed that in the docs. Solved
