### ISSUE TITLE
RFC: Card allows onClick event

### ISSUE THREAD

**Issue by kennandavison** [pinterest/gestalt#356]
Is clicking on a hovered card something Gestalt wants to support? Or would a Touchable wrapping (and a follow-up pr to make the focus outline line up with card's hover outline) be preferable?

**Comment by christianvuerings** [comment]
This is by design since we want the children inside of `Card` to be clickable: `Ideally all of the children should be clickable and cover 100% of the area`

https://gestalt.netlify.com/#/Card
