### ISSUE TITLE
Framer X support

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#370]
Our design system is Sketch-only right now, but a few designers have started exploring Framer. This is probably a good thing because Framer can run actual code :)

It seems like a common flow is to create a UI in Sketch, export it to Framer and then add interactivity that way. We might be able to support creating high-quality mocks in Framer first.

There's a few blockers to running Gestalt components inside Framer:

1. Framer doesn't understand Flowtype. This should be fine since we strip flowtype annotations anyway in `dist/` and ship vanilla ES5. Framer also expects components to be TypeScript modules. We can easily create TS wrapper files to export an API that Framer understands.

2. Components need a `propertyControls` field so that Framer can provide a nice UI for defining the component's input props. We can define this separately from the component:
```
import { TextField } from 'gestalt/dist/gestalt.js';

export class FramerTextField extends TextField {
  static propertyControls = {
    placeholder: { type: ControlType.String, title: 'placeholder' },
  }
}
```

3. CSS can be included with components like this:
```
import css from 'gestalt/dist/gestalt.css';
```
Then rendering:
```
<style dangerouslySetInnerHTML={{ __html: css }} />
```
into your component.

----

I was able to get up and running with a TextField (minus ErrorFlyout) in a relative short amount of time.

![screen shot 2018-09-20 at 4 08 43 pm](https://user-images.githubusercontent.com/5060341/45851419-a9656400-bcef-11e8-8e06-0dcaad6d6268.png)

Code [here.](https://gist.github.com/bradencanderson/5b6aae2d6b248aa17fb801f8f5c4d4e9)

**Comment by chrislloyd** [comment]
This is definitely cool but not on our roadmap. Closing for the moment.
