### ISSUE TITLE
<Box Layout examples are 66% copy+pastable

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/gestalt#38]
Originally from @ryan953 

New hires, or people unfamiliar with flexbox, unfamiliar with <Box>, css, etc. need more copy+pastable documentation. The Box/Layout section in this case.

See gestalt-box-layout.png for current rendering. It looks something like this:

 
    Layout
    Box uses Flexbox to achieve layout. If you're new to flex layout, please read the excellent CSS-Tricks guide to flexbox.

    justifyContent="start"
    alignItems="start"
    [ rendered example ]

 
The start/start example should say that `display={flex}` is also required to make these examples work. The complete examples should be:
 

    display="flex"
    justifyContent="start"
    alignItems="start"
    [ rendered example ]

The `display` param could be included as part of each example, or as a note in the paragraph above. Alternatively we could automatically add `display="flex"` whenever a flex property like `justifyContent` is used. This might have implications in the existing codebase.

**Comment by christianvuerings** [comment]
Closing out. Feel free to re-open if still relevant.
