### ISSUE TITLE
Gestalt <Box> should warn when using a special prop with the wrong/missing display/position/etc

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/gestalt#39]
Originally from @ryan953:

Some examples:

A <Box> with the `left` prop, ie:  <Box right>...</Box>, should have the corresponding `position="absolute"` set. Without the correct position, right={true} is invalid.

A <Box> with the `alignItems` prop, ie: <Box alignItems="center">...</Box> should have the corresponding `display="flex"` set. Without the correct display, the alignItems flag could interact unexpectedly with other parent elements, or would not change the render.

It is safe to ignore props like left when position is not set, and know that the render will not be affected with the addition of an extra prop which we do today. This however breaks encapsulation. With this example the final layout of the component will be different depending on the container. This is not desirable, the container should bring it's own layout and place the component within it.

This task is about adding feedback to users of <Box>. Users, in development mode, should get big red boxes whenever required fields are missing. In production we should continue to render as we do today. Also in production we should emit logs so we can identify instances where a property like `right` was added, but position was not. This may be an extra prop, or it may be a visual bug.

**Comment by bishwei** [comment]
@chrislloyd is this something we should warn or handle with flow?  this seems similar to the discussion we had before with `Sticky` where we decided against displaying a warning message

**Comment by chrislloyd** [comment]
Yep! I remember trying to do this originally but flow's support for disjoint unions was pretty off. I think we could try again and it would be a good UX win.

**Comment by christianvuerings** [comment]
Closing out. Feel free to re-open if still relevant.
