### ISSUE TITLE
Overriding Component Styling

### ISSUE THREAD

**Issue by lmick002** [pinterest/gestalt#416]
Is there any way to update/assign className to components and add custom styling to a component. For example, overriding the styling of a Textfield? Thanks.

**Comment by pfarejowicz** [comment]
Hi @lmick002, thanks for your question. Gestalt is meant to be a representation of Pinterest's design language and as such we limit the amount of custom stylings that can be applied as we want the components to represent the design stylings used here at Pinterest.

Besides the `dangerouslySetInlineStyle` prop on `<Box />` we do do not allow custom stylings on other components unfortunately. Hope that helps!
