### ISSUE TITLE
lightGray button color

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#44]
![Example](https://user-images.githubusercontent.com/5060341/37006037-3b09b5d4-208b-11e8-8e2c-a089175ef87f.png)

**Comment by christianvuerings** [comment]
@bradencanderson That should already be the case - the current `gray` is `lightGray`: https://github.com/pinterest/gestalt/blob/bb916d09685faf8a9ec0b3882a3acf8fe97edbf2/packages/gestalt/src/Button/Button.css#L50
