### ISSUE TITLE
Flyout anchor is null when the ref is on a Box

### ISSUE THREAD

**Issue by ishitagoel** [pinterest/gestalt#449]
I followed the example on https://pinterest.github.io/gestalt/#/Flyout as is, but it does not work. Console shows a warning that ref must not be assigned to a functional component. https://pinterest.github.io/gestalt/#/Box confirms that ref is not passed to div. What is the right way to do this?

**Comment by pfarejowicz** [comment]
Hi @ishitagoel, thanks for reporting. What version of gestalt are you using? The ability to set a ref on `Box` was added in `0.86.0`. Prior to that you would have been seeing that error.

As for the `Box` docs, good catch, those need to be updated to remove the comments about ref

**Comment by pfarejowicz** [comment]
`Box` docs updated/fixed in #450

**Comment by pfarejowicz** [comment]
Closed via #450 (will be deployed to docs pages on net release)
