### ISSUE TITLE
Warning on invalid prop type on TextField whilst using number as a type

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#482]
Failed prop type: Invalid prop `value` of type `number` supplied to `TextField`, expected `string`

Everything is working fine as expected but this warning keeps occurring. Any due diligence?

coz TextField does seem to accept number as a type.

**Comment by christianvuerings** [comment]
@zifahm would you be able to reproduce a test case? It's likely due to the flow or proptypes we set on `TextField`. https://codesandbox.io/s/gestalt-textfield-as-type-hw9e9
