### ISSUE TITLE
Default full width button seems to have rounded corners after update.

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#490]
The default full width button seems to have changed to rounded corners after update. 
Please try clicking on to see it in action. The checked pattern behind it seems to make it look like a rectangle.

current docs: https://pinterest.github.io/gestalt/#/Button
previous doc:  https://deploy-preview-413--gestalt.netlify.com/#/Button

Wondering if this is intended?

**Comment by pfarejowicz** [comment]
Hi @zifahm, its intentional via https://github.com/pinterest/gestalt/pull/476

@mminute or @collino have more info
