### ISSUE TITLE
How I can realized categories ?

### ISSUE THREAD

**Issue by Shoyadbek** [pinterest/gestalt#497]
How I can realized buttons after search? with component Button?
<img width="787" alt="Screen Shot 2019-03-16 at 16 39 01" src="https://user-images.githubusercontent.com/2202292/54474745-669dc800-480a-11e9-8851-28457185e8c9.png">

**Comment by btraut** [comment]
Really sorry @Shoyadbek. I don't understand your question. Can you try again?

**Comment by christianvuerings** [comment]
@Shoyadbek That would probably be a `<Link />` wrapping a`<Box />` with white test in it. Let us know if you need some more help
