### ISSUE TITLE
How can I style Touchable border?

### ISSUE THREAD

**Issue by ishitagoel** [pinterest/gestalt#498]
I want to change the border color and border size of the border that gets renders with <Touchable>. There is no property for this, and somehow I am unable to do this even through CSS.

**Comment by btraut** [comment]
I presume you're referring to the focus outline of Touchable? Gestalt is somewhat opinionated with regards to outlines for the sake of accessibility and consistency across all inputs. If you'd like to change those properties, I fear the best solution is to fork the package and modify the styles.

**Comment by ishitagoel** [comment]
Thank you!
