### ISSUE TITLE
Update documentation to use new example format

### ISSUE THREAD

**Issue by chrislloyd** [pinterest/gestalt#5]
We introduced a new live editable example format a while ago, but not every example has been updated. This issue is to keep track of our progress to converting all the examples.

- [x] Container
- [x] ErrorFlyout
- [x] Flyout
- [x] Heading
- [x] IconButton
- [x] Image
- [x] Label
- [x] Letterbox
- [x] Mask
- [x] Masonry
- [x] Modal
- [x] Pog
- [x] Pulsar
- [x] SearchField
- [x] SegmentedControl
- [x] SelectList
- [x] Spinner
- [x] Tabs
- [x] Text
- [x] TextArea
- [x] TextField
- [x] Toast
- [x] Tooltip

**Comment by blairanderson** [comment]
Looks great. 

Not sure if this is a relevant place to mention, individual component URL paths are broken on github pages https://pinterest.github.io/gestalt/

If you click a component it changes to https://pinterest.github.io/COMPONENT (example https://pinterest.github.io/Container ) which is not a valid path and redirects to the pinterest engineering page.

**Comment by chrislloyd** [comment]
@blairanderson sorry for the slow reply - great catch! It was fixed by @serranoarevalo in #88.

**Comment by chrislloyd** [comment]
All done.
