### ISSUE TITLE
How to use Flyout with React Hooks?

### ISSUE THREAD

**Issue by salmazov** [pinterest/gestalt#507]
I want to use Flyout in my Stateless Component with Hooks. But, how to use a ref?

**Comment by btraut** [comment]
Flyout expects a DOM element as a ref, and you won't have that ref on first render. As such, you'll need to do a two-stage render. Maybe this makes for an awkward API, but it should do the trick:

```
function MyComponent() {
  const [flyoutAnchor, setFlyoutAnchor] = useState(null);
  const myBoxRef = useRef();

  useEffect(() => {
    setFlyoutAnchor(myBoxRef.current);
  }, []);

  return (
    <>
      <Box ref={myBoxRef}>Flyout should be shown here!</Box>
      { flyoutAnchor && <Flyout anchor={flyoutAnchor}></Flyout> }
    <>
  );
}
```

**Comment by salmazov** [comment]
> Flyout expects a DOM element as a ref, and you won't have that ref on first render. As such, you'll need to do a two-stage render. Maybe this makes for an awkward API, but it should do the trick:
> 
> ```
> function MyComponent() {
>   const [flyoutAnchor, setFlyoutAnchor] = useState(null);
>   const myBoxRef = useRef();
> 
>   useEffect(() => {
>     setFlyoutAnchor(myBoxRef.current);
>   }, []);
> 
>   return (
>     <>
>       <Box ref={myBoxRef}>Flyout should be shown here!</Box>
>       { flyoutAnchor && <Flyout anchor={flyoutAnchor}>I'm flying!</Flyout> }
>     <>
>   );
> }
> ```

Thank you! It is working!

**Comment by zifahm** [comment]
I did it this way , is this wrong ?
``` 
function MyComponent() {
  const myBoxRef = useRef(null);


  return (
    <>
      <Box ref={myBoxRef}>Flyout should be shown here!</Box>
      { this.openOnClick && <Flyout anchor={myBoxRef.current}>I'm flying!</Flyout> }
    <>
  );
} 
```

**Comment by btraut** [comment]
@zifahm: That solution looks like it'd work fine, mostly because the Flyout isn't displayed on first render. The problem @salmazov was having was that the Flyout needed to be displayed without user interaction, and the ref isn't set on first render. If the Flyout is controlled by a click, you'll have an anchor ref set by the time the click actually happens.
