### ISSUE TITLE
Avatar doesn't re-render the image when src changes after an error

### ISSUE THREAD

**Issue by kimuraz** [pinterest/gestalt#514]
## What is it?
Probably a bug.

## Reproduction steps:
- Set a valid URL `src` on `<Avatar src={src} name="bla"/>`
- Then set the `src` to an invalid url
- Set it back to the previous (or any other) valid URL

## References
Maybe on the following line, the state changes due to the invalid URL, but it's never evaluated again, so it's quite impossible to dynamically change the `src` on Avatar component.

https://github.com/pinterest/gestalt/blob/3c9abb2fb525df2b9313ed7179318233b947f59c/packages/gestalt/src/Avatar.js#L85

Am I missing something? If not, may I correct this bug as a contribution?

Thanks in advance.

**Comment by btraut** [comment]
Looks like a bug to me. I'd be happy to accept a PR that resets `isImageLoaded` upon change of src.

**Comment by kimuraz** [comment]
On it :+1:

**Comment by christianvuerings** [comment]
@kimuraz could you confirm this is still an issue after we converted `Avatar` to use hooks? If so, feel free to re-open the issue and PR
