### ISSUE TITLE
Masonry

### ISSUE THREAD

**Issue by unicornxoxo1919** [pinterest/gestalt#538]
I don't know if this is a stupid question but what would be an example implementation of scrollContainer ?

**Comment by powerlanguage** [comment]
Hey @unicornxoxo1919 - here's a example of using `Masonry` with a `scrollContainer`: https://codesandbox.io/s/scroll-container-example-hg8qj

Let me know if you have any questions.

**Comment by unicornxoxo1919** [comment]
Thanks man , i'll take a stab at this after the 20th when exams are done.

You guys should put this in the official docs. For full reference implementation see that "codesandbox" :P 

Mind leaving this open until then ? Don't think i'll have an issue but you never know.

**Comment by unicornxoxo1919** [comment]
works like a charm.

although i'm using apollo and tried notifyOnNetworkStatusChange to be able to get the networkstatus to be able display a spinner when using fetchMore

for some reason that broke masonry

i get a react state error in masonry in console log :  
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.


anyway thanks for the help and props to you all at pinterest for open sourcing this
