### ISSUE TITLE
Using TextField with type password in a form breaks onSubmit

### ISSUE THREAD

**Issue by hainessss** [pinterest/gestalt#546]
Use case: Using TextField in a login form.  

Expected: Adding `onSubmit` to a `form` that surrounds a TextField, including those with `type='password'`, should resolve successfully upon a submit event.

Actual: 
<img width="598" alt="Screen Shot 2019-07-13 at 5 44 45 PM" src="https://user-images.githubusercontent.com/6373177/61177923-f0ca2300-a595-11e9-9d1d-b6b616a2c8cf.png">

Here's an example to reproduce.

```
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.handleChange = this._handleChange.bind(this);
    this.state = {
      value: ""
    };
  }
  _handleChange({ value }) {
    this.setState({ value });
  }
  _handleSubmit(event) {
    event.preventDefault();
  }
  render() {
    return (
      <Box>
        <Box marginBottom={2}>
          <Label htmlFor="name">
            <Text>Disabled</Text>
          </Label>
        </Box>
        <form onSubmit={this._handleSubmit}>
         <TextField
           id="name"
           type="password"
           onChange={this.handleChange}
           placeholder="Name"
           value={this.state.value}
         />
        </form>
      </Box>
    );
  }
}
```

**Comment by powerlanguage** [comment]
Hi @hainessss, I tried reproducing your issue, but couldn't: https://codesandbox.io/s/gestalt-j35zf

Would you be able to create a codesandbox that demonstrates the issue?

**Comment by hainessss** [comment]
@powerlanguage Yea weird, works in my Safari and on codesandbox. So maybe the problem is local to my chrome.  I will close and do some more trouble shooting. Thanks!

**Comment by hainessss** [comment]
Bug seems to be reproducible when using the last pass extension on chrome.
