### ISSUE TITLE
Add size to TextField

### ISSUE THREAD

**Issue by rjain15** [pinterest/gestalt#561]
I have a form with few text fields. How do I set the size of the text field? Enclosing in Box and dangerouslySetInnerHTML?

**Comment by christianvuerings** [comment]
@rjain15 We currently do not allow for multiple sizes of `TextField`. You can use custom CSS but we don't recommend it.

One thing that's important with input text fields is that they have a minimum font size of `16px` so it doesn't auto zoom on iOS. See https://uxcellence.com/2014/fix-ios-input-zoom for more info
