### ISSUE TITLE
negative margins applied by @media queries breaking layout 

### ISSUE THREAD

**Issue by mtycvy** [pinterest/gestalt#563]
Since upgrading to version 0.88.0 or any after, the layouts of some components (eg. searchfield) are broken due to negative margins being set

Strangely the rule causing the margins to break seems to be this one:

```
@media (min-width: 768px)
html:not([dir=rtl]) .JeA {
    margin-left: -48px;
}
```
which  doesn't seem to trigger on the official gestalt documentation page.

Any suggestions on how to fix this much appreciated.

**Comment by christianvuerings** [comment]
@mtycvy That might be due to the fact that your gestalt CSS file is out of sync with the gestalt JavaScript file. (e.g. due to bundler caching)

Could you submit a reproducible test case by forking the gestalt playground? https://codesandbox.io/s/k5plvp9v8v

**Comment by mtycvy** [comment]
it turns out my problem was to do with case sensitivity - the css contains classes JeA and Jea. Since i had not set <!doctype html> at the top of my html, this meant that html elements with class Jea applied were receiving rules defined in the CSS as class JeA

**Comment by christianvuerings** [comment]
@mtycvy Thank you for following up!
