### ISSUE TITLE
CSS Modules with Gestalt conflict

### ISSUE THREAD

**Issue by rbatsenko** [pinterest/gestalt#583]
Hello,

I'm trying to use `Gestalt` with `Next.js` and when I turn CSS Modules on in `next.config.js` (Next project config), Gestalt styles are not imported properly.
When CSS Modules config option is off, styles are properly imported and components work as expected.
As I understand it can be `webpack` issue, but I'm not sure.

Could someone please assist me on that?
Thanks!

**Comment by christianvuerings** [comment]
@rbatsenko Could you check whether this is still and issue? And if so, perhaps create a demo repository so we can investigate what's going on?
