### ISSUE TITLE
useState hook not working on TextField component

### ISSUE THREAD

**Issue by Emmandez** [pinterest/gestalt#584]
I've built a simple form using the TextField components for user input.
At first, the form was build as a class component, but when migrating to function components I realized the useState hook was not working as expected.

When updating a text field I'd get this error:
```
TypeError: Cannot read property 'value' of undefined
  46 | <TextField
  47 | id="apellidoPaterno"
  48 | autoComplete="off"
> 49 | onChange={(e)=>setLastName1(e.target.value)}
     | ^  50 | value={lastName1}
  51 | type="text"
  52 | />
```
Declaration of lastName1
```
import React, {useState} from 'react'; 
const [lastName1,setLastName1] = useState('');
```

I changed the TextField component with a simple HTML input and it worked ok.

This is only hapenning on function components. Class components are working just fine.

**Comment by btraut** [comment]
Oops, looks like there's a bug in your `onChange` handler. Gestalt is a little different than regular form elements in that its event handlers typically return an object with `event` being one of the properties.

Try this:
```
onChange={({event})=>setLastName1(event.target.value)}
```

**Comment by btraut** [comment]
@Emmandez: I'm closing this issue. Feel free to reopen if you're still seeing problems.
