### ISSUE TITLE
Adding error message handling to SearchField

### ISSUE THREAD

**Issue by themindfuldev** [pinterest/gestalt#617]
We are using `<SearchField>` as a form field, to select dynamically populated values, retrieved from a search term.

That's a required field for us, but since SearchField doesn't render error messages, we rebuilt a similar-looking error message on our parent component. 

However, this causes 2 problems:

1. On the rendered UI, we can't really add `aria-invalid` to the `<input>` field (since that's controlled by SearchField ), neither `aria-describedby` which should point to the error message.
1. Additional maintenance required on our error message look and feel, should gestalt's error message change.

Hence, I'd like to propose making SearchField behave like TextField for error state/error message, by:

- Adding 2 new optional props `hasError` and `errorMessage`. 
- Consuming them to populate `aria-invalid`, `aria-describedby` and including `<FormErrorMessage>`.
 
I'd be happy to work on it once I get an agreement from your side.

By doing this, we will be able to start verifying error states using `aria-invalid` on unit tests using RTL.

**Comment by christianvuerings** [comment]
@themindfuldev Feel free to go ahead an open a PR for this, we should use a similar approach as to TextField and TextArea

**Comment by themindfuldev** [comment]
Thank you so much @szatakia and @CalvinChhour !
