### ISSUE TITLE
The filter funtion should be deleted

### ISSUE THREAD

**Issue by xiezhongfu** [pinterest/gestalt#620]
https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Masonry.js#L498

**Comment by christianvuerings** [comment]
@xiezhongfu please add more details on why we should remove the filter function

**Comment by xiezhongfu** [comment]
> @xiezhongfu please add more details on why we should remove the filter function

the source code:
```js
items.filter(item => item)
```
the filter function is useless ???

**Comment by christianvuerings** [comment]
@xiezhongfu It does look like that's the case but it actually filters out items that are [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy). Without that line we would render falsy items.

You can try this out by running:
```javascript
[null, undefined, "", 'a', 'b'].filter(item => item)
// prints out: ["a", "b"]
```
