### ISSUE TITLE
Code sample UI obscures UI examples

### ISSUE THREAD

**Issue by ponori** [pinterest/gestalt#630]
The z-index of code samples seem to be "above" certain floating UI such as toasts and modals. 

<img width="1440" alt="Screenshot 2020-01-16 15 11 51" src="https://user-images.githubusercontent.com/50343812/72570737-8a8ac980-3872-11ea-8e35-bad0722678cd.png">

<img width="1438" alt="Screenshot 2020-01-16 14 49 39" src="https://user-images.githubusercontent.com/50343812/72570519-02a4bf80-3872-11ea-851e-c9a9bc92689d.png">

I've tested only toasts and modals, but there could very likely be additional cases where this issue arises.

cc @christianvuerings

**Comment by jennyscript** [comment]
Fixed by #639
