### ISSUE TITLE
How to use Flyout with anchor which is located on scrollable Layer?

### ISSUE THREAD

**Issue by krutoo** [pinterest/gestalt#650]
Hi. Tell me how to use Flyout inside Layer so that when scrolling through Layer content, Flyout is always near the anchor element? 

Sandbox with live example here: https://codesandbox.io/s/gestalt-flyout-layer-issue-uiz2k

**Comment by rootvar** [comment]
Not sure what your exception is for this behavior, but I don't think there is a clean way to preserve the flyout on scroll. It will either float on top of the hidden content (when the icon button is cropped out), or will get cropped itself.

So I would just hide the flyout on scroll:
`
                <Box
                  color="white"
                  padding={3}
                  width={400}
                  maxHeight={500}
                  overflow="scrollY"
                  onScroll={() => {
                    this.setState({ isPopupOpen: false })
                  }}
                >`

This can be optimized further by only setting state on scroll when the flyout is open.
