### ISSUE TITLE
Expose low-level Button styles

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#68]
Use case: building a Button with non-text children, e.g. an icon+text.

Right now it's super hard to build things that look like `Button` using just `Box` and `Touchable`.

Things that are hard to replicate:

- `border-radius`
- hover states.
- a11y

**Comment by chrislloyd** [comment]
Closing this out because while it's good feedback we don't have any plans around this at the moment. The original usecase (icons in buttons) keeps getting thrown around and might be valuable but we can re-open then.
