### ISSUE TITLE
Support relative value like "100vh" as top/bottom/left/right to Sticky component

### ISSUE THREAD

**Issue by ViolaCMU** [pinterest/gestalt#71]
currently it only support number as the parameter. Is it possible to support "100vg", "100%" etc?

**Comment by danedavid** [comment]
Can I work on this if it's being implemented ?

**Comment by chrislloyd** [comment]
This seems like an easy and good change :+1:

**Comment by danedavid** [comment]
then shall I take it ? will raise a PR soon!

**Comment by pfarejowicz** [comment]
Fixed by #166
