### ISSUE TITLE
Css modules Problem

### ISSUE THREAD

**Issue by alusicode** [pinterest/gestalt#712]
When i try to build the package with ```bash rollup -c rollup.config.js ```  it shows errors of some files not found.. those files are mostly css files that were  used in other css files with "compose"
and then the final minified css contains import statements 
like import "./Border.css"

what could be the issue please

**Comment by christianvuerings** [comment]
@alusicode to build the Gestalt CSS, run `yarn && yarn build` instead: https://github.com/pinterest/gestalt/blob/d602438b2982febb45c58592dac360c74534ebc0/package.json#L53

That will give you a minified `gestalt.css` file without `import statements: 
![image](https://user-images.githubusercontent.com/127199/75879871-0912da80-5dd1-11ea-9960-eddec1c51a8b.png)

Also make sure you use the correct Node.js version

**Comment by alusicode** [comment]
what version of node because i am still getting the error..
i am using node v12
