### ISSUE TITLE
Bring back smSize mdSize and lgSize for heading and Text 

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#719]
This would save a ton of code if you bring back smSize, mdSize and lgSize for Heading and Text

**Comment by christianvuerings** [comment]
@zifahm could you provide a bit more context on why it would save a lot of code for you?

`smSize` / `mdSize` and `lgSize` are legacy props on `Text`. Our philosophy is that text sizes should (for 99% of the cases) not be responsive.

**Comment by zifahm** [comment]
Oh okay, I get it now.
