### ISSUE TITLE
Pass additional props to the component in Masonry

### ISSUE THREAD

**Issue by Narutuffy** [pinterest/gestalt#874]
Right now only three fixed props are being passed to the component in masonry (those are `data: T`, `itemIdx: number`, and `isMeasuring: boolean`). There should be an optional additional props which could be sent to the component used by Masonry.

**Comment by btraut** [comment]
Can you tell me more about what you're trying to accomplish? There's two ways you could accomplish the same thing today:

1. `data` is already your property bag. As far as Masonry is concerned, there's no conceptual difference between `data` and other additional props, so you could just combine those into `data`. Just know that if you do this by creating objects, you should memoize those objects to prevent unstable `data` items on re-render.

2. While the `comp` function is expected to be pure and idempotent, you can break that expectation if you're careful. You could just have the `comp` function close over variables in the outer scope (either other local variables in a function component or even class properties such as state/props in a class component). The risk here is that updating those variables won't necessarily cause Masonry to re-render or to re-measure the affected items, so it's up to you to take more manual control.

**Comment by Narutuffy** [comment]
@btraut I want to highlight an external div when a `mouseover` event occurs on the`comp`. The way I want do it is by passing the ref of that external div to the `comp` and let it execute using that ref. How do you suggest I do it in this case.

**Comment by btraut** [comment]
What are you passing currently into `data`? Can you just pass the ref along with its corresponding data?

**Comment by Narutuffy** [comment]
Thank you that worked. You can close this issue.
