### ISSUE TITLE
accessibilityLabel not converting to aria-label

### ISSUE THREAD

**Issue by dmbrowne** [pinterest/gestalt#879]
```js
<Icon icon="cog" color="white" size="24px" accessibilityLabel="account settings" />
```

produced the following warning in the browser console:
`Warning: React does not recognize the `accessibilityLabel` prop on a DOM element`

But the prop seems to working in the gestalt playground, any ideas what I could be doing wrong.

I'm using version `1.55.1`

**Comment by christianvuerings** [comment]
@dmbrowne that usage looks correct to me, see https://codesandbox.io/s/example-956gf?file=/example.js for an example. Could you try to create a repro case yourself to showcase the issue?

As you can see in the screenshot, the `accessibilityLabel` will be converted into an `arial-label` on the `svg` element.
![image](https://user-images.githubusercontent.com/127199/82911057-45f9f380-9f20-11ea-90c1-67af6af530f0.png)
