### ISSUE TITLE
Add "ref" to <Touchable>, <Button> and <IconButton>

### ISSUE THREAD

**Issue by themindfuldev** [pinterest/gestalt#882]
I want to manually focus a `<Touchable>` area (which behaves as a large button) to improve accessibility keyboard tab order. I am able to add a `ref` to the parent Box and then get this element using `ref.current.firstChild` but I would really rather being able to add the `ref` directly to the `<Touchable>` element.

The same thing can be applied to `<Button>` and `<IconButton>`

In order for that to happen we would need to have `<Touchable>` to work with a `forwardRef`.

Here are some inputs by other Gestalt contributors:
- https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-to-dom-components
- Bump the major version since it's considered a breaking change: https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers
- Reference: `<Box>` already uses a `forwardRef`

**Comment by jackhsu978** [comment]
@themindfuldev `<TapArea>`, which is renamed from `<Touchable>`, supports refs. Please see the docs https://gestalt.netlify.app/#/TapArea for an example.

**Comment by themindfuldev** [comment]
Thanks @jackhsu978 ! I will close this ticket then.
