### ISSUE TITLE
IconButton a11y outline clips against nearby elements

### ISSUE THREAD

**Issue by bradencanderson** [pinterest/gestalt#92]
![screen shot 2018-03-20 at 3 29 32 pm](https://user-images.githubusercontent.com/5060341/37686205-9981798e-2c53-11e8-88e2-f40990a749f5.png)

The blue outline should probably display over the Button in this case.

**Comment by christianvuerings** [comment]
@bradencanderson According to design we should always have at least 1 boint of spacing between these which should fix this issue.
