### ISSUE TITLE
Documentation links don't seem to work

### ISSUE THREAD

**Issue by deoxxa** [pinterest/gestalt#95]
In several places there's a reference to https://pinterest.github.io/gestalt, but that redirects to https://engineering.pinterest.com/, which doesn't mention gestalt anywhere.

I did find the open source section, where I searched for "gestalt" via https://engineering.pinterest.com/open-source?combine=gestalt - but that seems to result in a broken page.

Where can I read the docs?

**Comment by chinanf-boy** [comment]
i got that issue too

**Comment by christianvuerings** [comment]
@deoxxa @chinanf-boy Thanks for reporting!

Previously we removed and then re-added the `gh-pages` branch which was causing downtime for our docs. #97 should fix that issue.

Closing this issue for now since https://pinterest.github.io/gestalt should be working again.
