### ISSUE TITLE
Checkbox color changes

### ISSUE THREAD

**Issue by ponori** [pinterest/gestalt#994]
<img width="259" alt="Screenshot 2020-07-08 09 39 30" src="https://user-images.githubusercontent.com/50343812/86947319-78426780-c100-11ea-872c-c4bf1d600349.png">

In the deselected state, the border color should be `colorGray100` (#494949)

<img width="261" alt="Screenshot 2020-07-08 10 02 43" src="https://user-images.githubusercontent.com/50343812/86948588-30bcdb00-c102-11ea-8d2b-36212f868c4b.png">

In the selected state, the border color should be `colorGray300` (#efefef)

**Comment by jennyscript** [comment]
Fixed by #1034
